name: gtsalpha_wallet
description: GtsAlpha Crypto Wallet + NFC + ID Scanner
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.19.0'

dependencies:
  flutter:
    sdk: flutter
  nfc_manager: ^3.5.0
  flutter_nfc_kit: ^3.3.3
  camera: ^0.11.0
  google_mlkit_text_recognition: ^0.13.0
  google_mlkit_face_detection: ^0.11.0
  google_mlkit_barcode_scanning: ^0.12.0
  mobile_scanner: ^5.2.3
  supabase_flutter: ^2.5.0
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5
  web3dart: ^2.7.3
  bip39: ^1.0.6
  bip32: ^2.0.0
  hex: ^0.2.0
  flutter_animate: ^4.5.0
  lottie: ^3.1.2
  permission_handler: ^11.3.1
  local_auth: ^2.3.0
  image_picker: ^1.1.2
  cached_network_image: ^3.3.1
  intl: ^0.19.0
  uuid: ^4.4.0
  http: ^1.2.1
  dio: ^5.6.0
  web_socket_channel: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.9

flutter:
  uses-material-design: true
  assets:
    - assets/animations/
    - assets/images/
    - assets/sounds/
